### ISSUE TITLE
Enhancement Ideea

### ISSUE THREAD

**Issue by ionut-maxim** [stefanstranger/Wunderlist#4]
Hello,
Just an ideea but some Set-* cmdlets would be useful :)
Hopefully I'll find some free time soon to help with a PR if that would work.

**Comment by stefanstranger** [comment]
You are right there are no Set-Wunderlist* functions created yet. Which one is most important to start with?

**Comment by stefanstranger** [comment]
Hi Maxim,

I created the following function to change a Wunderlist Task.

Please test and let me know if this is something you want in the next version.

Link to gist: https://gist.githubusercontent.com/stefanstranger/c2ee87e190c9dbad82e8663c83c70c7e/raw/98253e74c89ce01b79e6d2e3b694728c54472110/Set-WunderlistTask.ps1

Make sure you have installed the latest Wunderlist module from the PowerShell Gallery and to have the module loaded before testing the Set-WunderlistTask function.

/Stefan

**Comment by ionut-maxim** [comment]
Hey Stefan,
Haven't really tested it yet but it looks like what was missing from the modules.

**Comment by stefanstranger** [comment]
@bahaula let me know when you tested it so I can add it.
/Stefan

**Comment by ionut-maxim** [comment]
Hello @stefanstranger .

I've tested it. Had an issue with it:
```
Set-WunderlistTask : Cannot process argument transformation on parameter 'Id'. Cannot convert value "2475236383" 
to type "System.Int32". Error: "Value was either too large or too small for an Int32."
At \\blablabla.ps1:12 char:83
+ ... .title | Select-Object -First 1; Set-WunderlistTask -Id $_.id -revisi ...
+                                                             ~~~~~
    + CategoryInfo          : InvalidData: (:) [Set-WunderlistTask], ParameterBindingArgumentTransformationExcep 
   tion
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Set-WunderlistTask
```
I've changed **ID** from `int` to `long` and it worked.

**Comment by stefanstranger** [comment]
Hi Ionut,

Thanks for the feedback will fix it and relaase a new version soon.

/Stefan

**Comment by ionut-maxim** [comment]
Hey @stefanstranger , I've got one more question. Why am I being prompted to input a `MasterPassword` for every cmdlet I run?
